#不要直接替换整个文件, 只是添加下面的部分到你们的Configuration.yaml文件里面的sensor下面, 如果你们已经有sensor的类别请把下面的sensor删掉
sensor:
  - platform: template
    sensors:
      day:
        value_template: >
          {% set days = ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日"] %}
          
          {{ days[now().weekday()] }}

      month:
        value_template: >
          {% set months = ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"] %}
          
          {{ months[now().month-1] }}
          {{ strptime(states('sensor.date'), '%Y-%m-%d').day }}

      date_string:
        friendly_name: "Full Date"
        value_template: "{{ states('sensor.day') }} ,  {{ states('sensor.month') }}日"

 
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 192.168.50.230
    token: !secret roborock_token
    username: !secret xiaomi_id
    password: !secret xiaomi_pw
    country: "cn"
    draw: ["all"]
    colors:
      color_map_inside: [43, 47, 48]
      color_map_outside: [32, 36, 37]
      color_map_wall: [100, 196, 254]
      color_grey_wall: [216, 5, 69]
      color_path: [30, 80, 113]
      color_virtual_walls: [100, 196, 254]
      color_charger: [244, 103, 15]
      color_robo: [244, 244, 144]
      color_unknown: [0, 0, 0]
    map_transformation:
      rotate: 270

    attributes:
      - calibration_points
